//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int ID { get; set; }
        public int MaPhong { get; set; }
        public int Nam { get; set; }
        public int Thang { get; set; }
        public double TienPhong { get; set; }
        public double TienDien { get; set; }
        public double TienNuoc { get; set; }
        public double PhuPhi { get; set; }
        public string ChiTiet { get; set; }
        public bool DaThanhToan { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
