//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public string MaHopDong { get; set; }
        public string MaSinhVien { get; set; }
        public int MaPhong { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public bool DaKetThuc { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
